spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/ssm2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
