server:
  port: 8081
spring:
  profiles:
    active: dev
# 可以通过 debug = true 来查看，那鞋自动配置类生效，哪些没有生效
debug: true

---

server:
  port: 8082
spring:
  profiles: dev

---

server:
  port: 8083
spring:
  profiles: test

#person:
#  name: qinjiang@qq.com
#  age: ${random.int}
#  happy: false
#  birth: 2019/11/02
#  maps: {k1: v1, k2: v2}
#  lists:
#    - code
#    - music
#    - girl
#  dog:
#    name: ${person.hello:hello}
#    age: 3
#
#dog:
#  first-name: 小河
#  age: 3